influxdb:
  url: ${INFLUXDB_URL:http://influxdb:8086}
  token: ${INFLUXDB_TOKEN:chaussec-super-secret-token-2026}
  org: ${INFLUXDB_ORG:chaussec}
  bucket: ${INFLUXDB_BUCKET:chaussec_metrics}

opensearch:
  url: ${OPENSEARCH_URL:http://opensearch:9200}

spring:
  application:
    name: backend
  ldap:
    urls: ${LDAP_URL:ldap://localhost:389}
    base: ${LDAP_BASE_DN:dc=chaussec,dc=eu}
    username: ${LDAP_ADMIN_DN:cn=admin,dc=chaussec,dc=eu}
    password: ${LDAP_ADMIN_PASSWORD:adminpassword}
  