[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/log/suricata/eve.json
    Parser            json
    Tag               suricata
    DB                /var/flb_suricata.db
    Mem_Buf_Limit     5MB

[OUTPUT]
    Name                  gelf
    Match                 *
    Host                  graylog
    Port                  12201
    Mode                  udp
    Gelf_Short_Message_Key event_type
