apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://opensearch:9200
    database: "graylog_*"
    jsonData:
      timeField: "timestamp"
      esVersion: 7100

  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: chaussec
      defaultBucket: chaussec_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: chaussec-super-secret-token-2026
